- pyproject.toml
- tase/common/preprocessing.py
- tase/common/utils.py
- tase/db/arangodb/graph/vertices/audio.py
- tase/db/elasticsearchdb/models/audio.py
- tase/tase_client.py
- tase/telegram/client/tasks/extract_usernames_task.py
- tase/telegram/client/tasks/index_audios_task.py
This update closes issue #41 and updates project dependencies. On top of that, some codes are refactored. Instead of calling a variety of functions to clean different patterns of data, a pipeline of functions is used to clean the text with one function. Different functions can be used in defining a pipeline list to get desirable results.
> + Resolve #41

- tase/common/preprocessing.py
- tase/db/arangodb/graph/vertices/audio.py
- tase/db/elasticsearchdb/models/audio.py
- tase/telegram/bots/ui/templates/audio_caption_template.py
> + Resolve #45

- tase/common/preprocessing.py
- tase/common/utils.py
- tase/db/arangodb/enums/mention_source.py
- tase/db/arangodb/graph/edges/__init__.py
- tase/db/arangodb/graph/edges/has_hashtag.py
- tase/db/arangodb/graph/vertices/__init__.py
- tase/db/arangodb/graph/vertices/audio.py
- tase/db/arangodb/graph/vertices/hashtag.py
> + Resolve #47

- tase/common/utils.py
- tase/db/arangodb/base/base_collection_document.py
- tase/db/arangodb/graph/vertices/query.py
- tase/db/arangodb/graph/vertices/user.py
- tase/telegram/bots/bot_commands/admin/add_channel_command.py
- tase/telegram/bots/bot_commands/admin/shutdown_command.py
- tase/telegram/bots/bot_commands/base_command.py
- tase/telegram/bots/bot_commands/general/dummy_command.py
- tase/telegram/bots/bot_commands/general/help_command.py
- tase/telegram/bots/bot_commands/general/home_command.py
- tase/telegram/bots/bot_commands/general/language_command.py
- tase/telegram/bots/bot_commands/general/start_command.py
- tase/telegram/client/client_manager.py
- tase/telegram/client/telegram_client.py
In this update, the `BaseCommand` subclasses in the `tase/telegram/bots/` package were updated to include all attributes needed for setting a telegram bot command by adding a new attribute named `command_description`. In addition, the `dummy_command` minimum required role level was updated to be available only to users with `admin` role.
> + Close #15

- tase/common/utils.py
- tase/telegram/bots/bot_commands/admin/__init__.py
- tase/telegram/bots/bot_commands/admin/index_channel_command.py
- tase/telegram/bots/bot_commands/bot_command_type.py
> + Resolve #59

- .gitignore
- tase/db/arangodb/graph/edges/to_bot.py
- tase/db/arangodb/graph/vertices/playlist.py
- tase/static/emoji.py
- tase/telegram/bots/inline/inline_search.py
- tase/telegram/bots/ui/inline_buttons/__init__.py
- tase/telegram/bots/ui/inline_buttons/add_to_playlist_button.py
- tase/telegram/bots/ui/inline_buttons/base/inline_button_type.py
- tase/telegram/bots/ui/inline_buttons/common/utils.py
- tase/telegram/bots/ui/inline_buttons/remove_from_playlist_button.py
- tase/telegram/bots/ui/inline_buttons/toggle_favorite_playlist.py
- tase/telegram/bots/ui/inline_items/audio_item.py
- tase/telegram/update_handlers/bots/bot_message_handler.py
> + Resolve #25

- tase/telegram/bots/ui/inline_buttons/toggle_dislike_audio_button.py
- tase/telegram/bots/ui/inline_buttons/toggle_favorite_playlist.py
- tase/telegram/bots/ui/inline_buttons/toggle_like_audio_button.py
- tase/telegram/bots/ui/inline_items/audio_item.py
- tase/telegram/update_handlers/bots/callback_query_handler.py
- tase/telegram/update_handlers/bots/chosen_inline_query_handler.py
> # Close #24

- tase/static/emoji.py
- tase/telegram/bots/bot_commands/general/start_command.py
- tase/telegram/bots/inline/inline_search.py
- tase/telegram/bots/ui/inline_buttons/__init__.py
- tase/telegram/bots/ui/inline_buttons/base/inline_button.py
- tase/telegram/bots/ui/inline_buttons/base/inline_button_type.py
- tase/telegram/bots/ui/inline_buttons/common/utils.py
- tase/telegram/bots/ui/inline_buttons/download_audio_button.py
- tase/telegram/bots/ui/inline_items/audio_item.py
- tase/telegram/update_handlers/base/base_handler.py
- tase/telegram/update_handlers/bots/bot_message_handler.py
> + Resolve #67

- tase/telegram/bots/inline/inline_search.py
- tase/telegram/bots/ui/inline_buttons/add_to_playlist_button.py
- tase/telegram/bots/ui/inline_buttons/base/inline_button.py
- tase/telegram/bots/ui/inline_buttons/common/__init__.py
- tase/telegram/bots/ui/inline_buttons/common/utils.py
- tase/telegram/bots/ui/inline_buttons/my_playlists_button.py
- tase/telegram/bots/ui/inline_buttons/remove_from_playlist_button.py
- tase/telegram/bots/ui/inline_items/audio_item.py
- tase/telegram/bots/ui/inline_items/playlist_item.py
- tase/telegram/update_handlers/base/base_handler.py
> + Close #65

- tase/telegram/bots/ui/inline_buttons/back_to_playlists_button.py
- tase/telegram/bots/ui/inline_buttons/my_playlists_button.py
> + Resolve #71

- tase/telegram/bots/bot_commands/bot_command_type.py
- tase/telegram/bots/bot_commands/general/__init__.py
- tase/telegram/bots/bot_commands/general/cancel_task_command.py
- tase/telegram/bots/ui/inline_buttons/add_to_playlist_button.py
- tase/telegram/bots/ui/inline_buttons/delete_playlist_button.py
- tase/telegram/bots/ui/inline_buttons/edit_playlist_description_button.py
- tase/telegram/bots/ui/inline_buttons/edit_playlist_title_button.py
- tase/telegram/bots/ui/inline_buttons/my_playlists_button.py
> + Resolve #72

- tase/db/arangodb/graph/vertices/user.py
- tase/telegram/bots/bot_commands/admin/__init__.py
- tase/telegram/bots/bot_commands/admin/demote_user_command.py
- tase/telegram/bots/bot_commands/admin/promote_user_command.py
- tase/telegram/bots/bot_commands/bot_command_type.py
- tase/telegram/client/telegram_client.py
> Resolve #74

- tase/db/arangodb/base/base_collection_document.py
- tase/db/arangodb/graph/vertices/user.py
- tase/telegram/bots/bot_commands/admin/demote_user_command.py
- tase/telegram/bots/bot_commands/admin/promote_user_command.py
- tase/telegram/bots/bot_commands/base_command.py
This update closes issue #77 and Fixes a bug in updating arango document objects
> + Resolve #77

- tase/db/arangodb/graph/vertices/chat.py
- tase/db/arangodb/graph/vertices/user.py
- tase/telegram/bots/bot_commands/admin/demote_user_command.py
- tase/telegram/bots/bot_commands/admin/promote_user_command.py
- tase/telegram/bots/bot_commands/base_command.py
- tase/telegram/bots/bot_commands/general/start_command.py
- tase/telegram/client/client_manager.py
- tase/telegram/update_handlers/bots/bot_message_handler.py
- tase/telegram/update_handlers/bots/callback_query_handler.py
- tase/telegram/update_handlers/bots/chosen_inline_query_handler.py
- tase/telegram/update_handlers/bots/inline_query_handler.py
This update closes issue #79 and fixes an issue in finding users by their username in the ArangoDB
> + Resolve #79

- tase/db/arangodb/graph/vertices/playlist.py
- tase/telegram/bots/ui/inline_buttons/common/utils.py
- tase/telegram/bots/ui/inline_buttons/remove_from_playlist_button.py
- tase/telegram/update_handlers/bots/bot_message_handler.py
This update closes issue #51 and Fixes an issue in removing audios from playlists.
> + Resolve #51

- tase/db/arangodb/graph/vertices/playlist.py
- tase/telegram/bots/ui/inline_buttons/add_to_playlist_button.py
- tase/telegram/bots/ui/inline_buttons/common/utils.py
> + Resolve #52

- tase/common/preprocessing.py
- tase/telegram/update_handlers/bots/bot_message_handler.py
> + Resolve #49

- tase/db/arangodb/graph/vertices/audio.py
- tase/db/db_utils.py
- tase/db/elasticsearchdb/models/audio.py
- tase/db/elasticsearchdb/models/base_document.py
- tase/telegram/bots/bot_commands/admin/add_channel_command.py
- tase/telegram/bots/bot_commands/admin/index_channel_command.py
- tase/telegram/bots/inline/custom_inline_query_result.py
- tase/telegram/bots/inline/inline_search.py
- tase/telegram/bots/ui/inline_buttons/toggle_dislike_audio_button.py
- tase/telegram/bots/ui/inline_buttons/toggle_favorite_playlist.py
- tase/telegram/bots/ui/inline_buttons/toggle_like_audio_button.py
- tase/telegram/bots/ui/inline_items/playlist_item.py
- tase/telegram/bots/ui/templates/audio_caption_template.py
- tase/telegram/bots/ui/templates/query_results_template.py
- tase/telegram/client/tasks/add_channel_task.py
- tase/telegram/client/tasks/index_audios_task.py
- tase/telegram/update_handlers/bots/bot_message_handler.py
This update closes issue #85 and fixes a few bugs.
> Resolve #85

- pyproject.toml
- tase/common/preprocessing.py
- tase/db/arangodb/graph/vertices/audio.py
- tase/db/arangodb/helpers/__init__.py
- tase/db/arangodb/helpers/bit_rate_type.py
- tase/db/elasticsearchdb/models/audio.py
- tase/static/emoji.py
- tase/telegram/bots/inline/inline_search.py
- tase/telegram/bots/ui/templates/audio_caption_template.py
- tase/telegram/bots/ui/templates/query_results_template.py
- tase/telegram/update_handlers/bots/inline_query_handler.py
This update closes issue #84 and fixes a few bugs.
> Resolve #84

- tase/common/preprocessing.py
- tase/db/arangodb/document/__init__.py
- tase/db/arangodb/document/audio_inline_message.py
- tase/db/arangodb/helpers/__init__.py
- tase/db/arangodb/helpers/audio_keyboard_status.py
- tase/telegram/bots/inline/inline_search.py
- tase/telegram/bots/ui/inline_buttons/base/inline_button.py
- tase/telegram/bots/ui/inline_buttons/common/utils.py
- tase/telegram/bots/ui/inline_buttons/toggle_dislike_audio_button.py
- tase/telegram/bots/ui/inline_buttons/toggle_favorite_playlist.py
- tase/telegram/bots/ui/inline_buttons/toggle_like_audio_button.py
- tase/telegram/bots/ui/inline_items/audio_item.py
- tase/telegram/update_handlers/base/base_handler.py
- tase/telegram/update_handlers/bots/chosen_inline_query_handler.py
> + Resolve #66

- tase/db/arangodb/document/audio_inline_message.py
- tase/db/arangodb/graph/vertices/audio.py
- tase/db/arangodb/graph/vertices/playlist.py
- tase/telegram/bots/inline/custom_inline_query_result.py
- tase/telegram/bots/ui/inline_buttons/common/utils.py
- tase/telegram/bots/ui/inline_buttons/download_history_button.py
- tase/telegram/bots/ui/inline_buttons/get_playlist_audios_button.py
- tase/telegram/update_handlers/bots/chosen_inline_query_handler.py
In this update, a bug in creating inline message documents in the ArangoDB and another bug in paginating items in the inline mode were fixed.
> Fix a few bugs

- docker-compose.yml
- tase/db/arangodb/base/base_collection_document.py
- tase/db/arangodb/document/__init__.py
- tase/db/arangodb/document/bot_task.py
- tase/db/arangodb/document/rabbitmq_task.py
- tase/db/arangodb/enums/__init__.py
- tase/db/arangodb/enums/rabbitmq_task_status.py
- tase/db/arangodb/enums/rabbitmq_task_type.py
- tase/scheduler/jobs/__init__.py
- tase/scheduler/jobs/base_job.py
- tase/scheduler/jobs/check_usernames_job.py
- tase/scheduler/jobs/dummy_job.py
- tase/scheduler/jobs/extract_usernames_job.py
- tase/scheduler/jobs/index_audios_job.py
- tase/scheduler/jobs/index_channels_job.py
- tase/scheduler/scheduler.py
- tase/task_distribution/__init__.py
- tase/task_distribution/base_task.py
- tase/task_distribution/shutdown_task.py
- tase/task_distribution/target_worker_type.py
- tase/telegram/bots/bot_commands/admin/add_channel_command.py
- tase/telegram/bots/bot_commands/admin/index_channel_command.py
- tase/telegram/bots/bot_commands/admin/shutdown_command.py
- tase/telegram/bots/bot_commands/general/dummy_command.py
- tase/telegram/client/client_worker.py
- tase/telegram/tasks/add_channel_task.py
- tase/telegram/tasks/check_usernames_task.py
- tase/telegram/tasks/dummy_task.py
- tase/telegram/tasks/extract_usernames_task.py
- tase/telegram/tasks/index_audios_task.py
> Resolve #97

- tase/db/arangodb/document/job.py
- tase/db/arangodb/document/rabbitmq_task.py
- tase/db/arangodb/enums/rabbitmq_task_type.py
- tase/db/arangodb/graph/vertices/hit.py
- tase/db/arangodb/helpers/__init__.py
- tase/db/arangodb/helpers/hit_count.py
- tase/db/elasticsearchdb/models/audio.py
- tase/scheduler/jobs/__init__.py
- tase/scheduler/jobs/count_hits_job.py
- tase/scheduler/scheduler.py
- tase/tase_client.py
> Resolve #19

- requirements.txt
- tase/db/arangodb/graph/vertices/audio.py
- tase/db/arangodb/graph/vertices/interaction.py
- tase/db/arangodb/helpers/audio_keyboard_status.py
- tase/db/database_client.py
- tase/telegram/bots/ui/inline_buttons/toggle_dislike_audio_button.py
- tase/telegram/bots/ui/inline_buttons/toggle_like_audio_button.py
- tase/telegram/tasks/index_audios_task.py
This update closes issue #102.
> Resolve #102

- tase/db/arangodb/base/base_collection_document.py
- tase/db/arangodb/graph/vertices/interaction.py
- tase/db/arangodb/helpers/interaction_count.py
- tase/db/elasticsearchdb/models/audio.py
- tase/db/elasticsearchdb/models/base_document.py
- tase/telegram/tasks/check_usernames_task.py
This update closes issue #101.
> Resolve #101

- tase/db/arangodb/graph/edges/mentions.py
- tase/db/arangodb/graph/vertices/chat.py
- tase/db/arangodb/graph/vertices/username.py
- tase/scheduler/jobs/index_audios_job.py
- tase/telegram/bots/bot_commands/admin/__init__.py
- tase/telegram/bots/bot_commands/admin/extract_usernames_command.py
- tase/telegram/bots/bot_commands/bot_command_type.py
- tase/telegram/tasks/extract_usernames_task.py
This update closes issue #103.
> Resolve #103

- tase/db/arangodb/graph/vertices/chat.py
- tase/scheduler/jobs/extract_usernames_job.py
- tase/telegram/bots/bot_commands/admin/__init__.py
- tase/telegram/bots/bot_commands/admin/check_usernames_command.py
- tase/telegram/bots/bot_commands/bot_command_type.py
- tase/telegram/tasks/extract_usernames_task.py
This update closes issue #104.
> Resolve #104

- tase/common/utils.py
- tase/db/arangodb/enums/rabbitmq_task_type.py
- tase/db/arangodb/graph/vertices/username.py
- tase/scheduler/jobs/__init__.py
- tase/scheduler/jobs/check_usernames_job.py
- tase/scheduler/jobs/check_usernames_with_unchecked_mentions_job.py
- tase/telegram/bots/bot_commands/admin/check_usernames_command.py
- tase/telegram/tasks/__init__.py
- tase/telegram/tasks/check_usernames_task.py
- tase/telegram/tasks/extract_usernames_task.py
This update closes issue #111.
> Resolve #111

- tase/common/preprocessing.py
- tase/common/utils.py
- tase/db/arangodb/base/base_collection_document.py
- tase/db/arangodb/graph/edges/mentions.py
- tase/db/arangodb/graph/vertices/username.py
- tase/scheduler/jobs/check_usernames_job.py
- tase/scheduler/jobs/check_usernames_with_unchecked_mentions_job.py
- tase/scheduler/jobs/extract_usernames_job.py
- tase/telegram/tasks/check_usernames_task.py
This update closes issue #113.
> Resolve #113

- tase/db/arangodb/base/base_collection_document.py
- tase/db/arangodb/graph/vertices/chat.py
- tase/db/elasticsearchdb/models/audio.py
- tase/db/elasticsearchdb/models/base_document.py
- tase/telegram/bots/ui/inline_buttons/base/inline_button_type.py
- tase/telegram/tasks/add_channel_task.py
- tase/telegram/tasks/check_usernames_task.py
- tase/telegram/tasks/extract_usernames_task.py
- tase/telegram/tasks/index_audios_task.py
- tase/telegram/update_handlers/bots/bot_message_handler.py
- tase/telegram/update_handlers/bots/inline_query_handler.py
This update closes issue #107.
> Resolve #107

- tase/telegram/bots/inline/custom_inline_query_result.py
- tase/telegram/bots/inline/inline_search.py
- tase/telegram/bots/ui/inline_buttons/add_to_playlist_button.py
- tase/telegram/bots/ui/inline_buttons/back_to_playlists_button.py
- tase/telegram/bots/ui/inline_buttons/common/utils.py
- tase/telegram/bots/ui/inline_buttons/download_history_button.py
- tase/telegram/bots/ui/inline_buttons/get_playlist_audios_button.py
- tase/telegram/bots/ui/inline_buttons/help_catalog.py
- tase/telegram/bots/ui/inline_buttons/my_playlists_button.py
- tase/telegram/bots/ui/inline_buttons/remove_from_playlist_button.py
- tase/telegram/bots/ui/inline_items/__init__.py
- tase/telegram/bots/ui/inline_items/audio_in_no_playlist_item.py
> Resolve #93

- tase/telegram/update_handlers/bots/bot_message_handler.py
This update closes issue #115.
> Resolve #115

- tase/db/arangodb/graph/vertices/audio.py
- tase/db/arangodb/graph/vertices/query.py
- tase/db/arangodb/graph/vertices/user.py
- tase/static/emoji.py
- tase/telegram/bots/bot_commands/admin/__init__.py
- tase/telegram/bots/bot_commands/admin/check_bot_status_command.py
- tase/telegram/bots/bot_commands/bot_command_type.py
- tase/telegram/bots/ui/templates/__init__.py
- tase/telegram/bots/ui/templates/bot_status_template.py
This update closes issue #114.
> Resolve #114

- tase/db/arangodb/graph/vertices/username.py
This update close issue #125 and fixes minor bug in the `get_checked_usernames_with_unchecked_mentions` method of the `username` module
> Resolve #125

- tase/db/arangodb/graph/vertices/username.py
- tase/db/arangodb/helpers/elastic_query_metadata.py
- tase/scheduler/jobs/check_usernames_job.py
- tase/scheduler/jobs/check_usernames_with_unchecked_mentions_job.py
- tase/scheduler/jobs/count_hits_job.py
- tase/scheduler/jobs/count_interactions_job.py
- tase/scheduler/jobs/dummy_job.py
- tase/scheduler/jobs/extract_usernames_job.py
- tase/scheduler/jobs/index_audios_job.py
- tase/scheduler/scheduler.py
- tase/task_distribution/base_task.py
- tase/task_distribution/shutdown_task.py
- tase/telegram/client/client_worker.py
- tase/telegram/tasks/add_channel_task.py
- tase/telegram/tasks/check_usernames_task.py
- tase/telegram/tasks/extract_usernames_task.py
- tase/telegram/tasks/index_audios_task.py
This update closes issue #127.
> Resolve #127

- tase/db/arangodb/base/base_collection_document.py
- tase/db/arangodb/graph/vertices/audio.py
- tase/db/arangodb/graph/vertices/hit.py
- tase/db/arangodb/graph/vertices/interaction.py
- tase/db/arangodb/graph/vertices/playlist.py
- tase/db/arangodb/graph/vertices/query.py
- tase/db/arangodb/helpers/audio_keyboard_status.py
- tase/db/elasticsearchdb/models/audio.py
- tase/errors/__init__.py
- tase/errors/audio_vertex_does_not_exists.py
- tase/telegram/bots/inline/custom_inline_query_result.py
- tase/telegram/bots/inline/inline_search.py
- tase/telegram/bots/ui/inline_buttons/add_to_playlist_button.py
- tase/telegram/bots/ui/inline_buttons/back_to_playlists_button.py
- tase/telegram/bots/ui/inline_buttons/common/utils.py
- tase/telegram/bots/ui/inline_buttons/download_history_button.py
- tase/telegram/bots/ui/inline_buttons/get_playlist_audios_button.py
- tase/telegram/bots/ui/inline_buttons/help_catalog.py
- tase/telegram/bots/ui/inline_buttons/my_playlists_button.py
- tase/telegram/bots/ui/inline_buttons/remove_from_playlist_button.py
- tase/telegram/bots/ui/inline_buttons/toggle_dislike_audio_button.py
- tase/telegram/bots/ui/inline_buttons/toggle_favorite_playlist.py
- tase/telegram/bots/ui/inline_buttons/toggle_like_audio_button.py
- tase/telegram/bots/ui/inline_items/audio_item.py
- tase/telegram/bots/ui/templates/query_results_template.py
- tase/telegram/tasks/extract_usernames_task.py
- tase/telegram/tasks/index_audios_task.py
- tase/telegram/update_handlers/base/base_handler.py
- tase/telegram/update_handlers/bots/bot_message_handler.py
- tase/telegram/update_handlers/bots/inline_query_handler.py
This update closes issue #129.
> Resolve #129

- tase/common/preprocessing.py
- tase/common/utils.py
- tase/db/arangodb/base/base_collection_document.py
- tase/db/arangodb/graph/vertices/audio.py
- tase/db/arangodb/graph/vertices/hit.py
- tase/db/arangodb/graph/vertices/user.py
- tase/telegram/bots/bot_commands/admin/add_channel_command.py
- tase/telegram/bots/bot_commands/admin/demote_user_command.py
- tase/telegram/bots/bot_commands/admin/extract_usernames_command.py
- tase/telegram/bots/bot_commands/admin/index_channel_command.py
- tase/telegram/bots/bot_commands/admin/promote_user_command.py
- tase/telegram/tasks/dummy_task.py
- tase/telegram/tasks/extract_usernames_task.py
- tase/telegram/update_handlers/bots/bot_message_handler.py
This update closes issue #131.
> Resolve #131

- .env_sample
- pyproject.toml
- tase/common/utils.py
- tase/errors/__init__.py
- tase/errors/not_enough_ram_error.py
- tase/scheduler/jobs/check_usernames_job.py
- tase/scheduler/jobs/extract_usernames_job.py
- tase/scheduler/jobs/index_audios_job.py
- tase/tase_client.py
- tase/task_distribution/base_task.py
- tase/telegram/bots/bot_commands/admin/add_channel_command.py
- tase/telegram/bots/bot_commands/admin/check_usernames_command.py
- tase/telegram/bots/bot_commands/admin/extract_usernames_command.py
- tase/telegram/bots/bot_commands/admin/index_channel_command.py
- tase/telegram/bots/bot_commands/admin/shutdown_command.py
- tase/telegram/bots/bot_commands/general/dummy_command.py
This update closes issue #133.
> Resolve 133

- tase/db/arangodb/graph/vertices/playlist.py
- tase/telegram/bots/ui/inline_buttons/__init__.py
- tase/telegram/bots/ui/inline_buttons/base/inline_button_type.py
- tase/telegram/bots/ui/inline_buttons/common/__init__.py
- tase/telegram/bots/ui/inline_buttons/common/utils.py
- tase/telegram/bots/ui/inline_buttons/show_more_results_button.py
- tase/telegram/update_handlers/bots/bot_message_handler.py
- tase/telegram/update_handlers/bots/chosen_inline_query_handler.py
This update closes issue #147.
> Resolve #147

- tase/db/arangodb/document/__init__.py
- tase/db/arangodb/document/playlist_inline_message.py
- tase/telegram/bots/ui/inline_buttons/__init__.py
- tase/telegram/bots/ui/inline_buttons/base/inline_button_type.py
- tase/telegram/bots/ui/inline_buttons/common/utils.py
- tase/telegram/bots/ui/inline_buttons/my_playlists_button.py
- tase/telegram/bots/ui/inline_buttons/toggle_playlist_settings_button.py
> Resolve #86

- tase/db/elasticsearchdb/models/audio.py
- tase/db/elasticsearchdb/models/playlist.py
- tase/telegram/bots/ui/base/base_inline_button_data.py
- tase/telegram/bots/ui/inline_buttons/add_to_playlist_button.py
- tase/telegram/bots/ui/inline_buttons/back_to_playlists_button.py
- tase/telegram/bots/ui/inline_buttons/download_history_button.py
- tase/telegram/bots/ui/inline_buttons/get_playlist_audios_button.py
- tase/telegram/bots/ui/inline_buttons/help_catalog.py
- tase/telegram/bots/ui/inline_buttons/my_playlist_subscriptions.py
- tase/telegram/bots/ui/inline_buttons/my_playlists_button.py
- tase/telegram/bots/ui/inline_buttons/remove_from_playlist_button.py
- tase/telegram/bots/ui/inline_buttons/search_among_public_playlists_button.py
- tase/telegram/bots/ui/inline_buttons/share_playlist_button.py
- tase/telegram/bots/ui/inline_buttons/show_more_results_button.py
- tase/telegram/update_handlers/bots/inline_query_handler.py
This update adds support for searching audio files by hashtag.
> Resolve #152

- tase/telegram/bots/ui/base/base_inline_button.py
- tase/telegram/bots/ui/inline_buttons/back_to_playlists_button.py
- tase/telegram/bots/ui/inline_buttons/download_history_button.py
- tase/telegram/bots/ui/inline_buttons/my_playlist_subscriptions.py
- tase/telegram/bots/ui/inline_buttons/my_playlists_button.py
- tase/telegram/bots/ui/inline_buttons/search_among_public_playlists_button.py
- tase/telegram/update_handlers/bots/inline_query_handler.py
In this update, support for adding multiple aliases for inline commands was added.
> Resolve #154

- tase/db/arangodb/enums/interaction_type.py
- tase/db/arangodb/graph/vertices/interaction.py
- tase/db/elasticsearchdb/models/playlist.py
- tase/telegram/bots/ui/inline_buttons/get_playlist_audios_button.py
- tase/telegram/bots/ui/inline_buttons/search_among_public_playlists_button.py
This update resolve issue #160.
> Resolve #160

- tase/common/utils.py
- tase/configs/tase_config.py
- tase/db/arangodb/document/__init__.py
- tase/db/arangodb/document/thumbnail.py
- tase/db/arangodb/graph/vertices/__init__.py
- tase/db/arangodb/graph/vertices/audio.py
- tase/db/arangodb/graph/vertices/audio_interaction.py
- tase/db/arangodb/graph/vertices/playlist.py
- tase/db/arangodb/graph/vertices/thumbnail.py
- tase/db/database_client.py
- tase/db/db_utils.py
- tase/db/elasticsearchdb/models/audio.py
- tase/telegram/bots/ui/inline_buttons/add_to_playlist_button.py
- tase/telegram/bots/ui/inline_buttons/common/utils.py
- tase/telegram/bots/ui/inline_buttons/get_playlist_audios_button.py
- tase/telegram/bots/ui/inline_items/audio_item.py
- tase/telegram/client/telegram_client.py
- tase/telegram/client/telegram_client_manager.py
- tase/telegram/tasks/forward_message_task.py
- tase/telegram/tasks/index_audios_task.py
- tase/telegram/update_handlers/base/base_handler.py
- tase/telegram/update_handlers/bots/chosen_inline_query_handler.py
> Resolve #94

- tase/db/arangodb/graph/vertices/playlist.py
- tase/telegram/bots/ui/inline_buttons/common/utils.py
- tase/telegram/bots/ui/inline_buttons/my_playlist_subscriptions.py
In this update, issue #169 has been resolved.
> Resolve issue #169

- tase/common/utils.py
- tase/db/arangodb/document/downloaded_thumbnail_file.py
- tase/db/arangodb/graph/vertices/audio.py
- tase/db/arangodb/graph/vertices/thumbnail.py
- tase/db/arangodb/graph/vertices/thumbnail_file.py
- tase/db/database_client.py
- tase/db/elasticsearchdb/models/audio.py
- tase/telegram/bots/ui/inline_buttons/my_playlists_button.py
- tase/telegram/tasks/upload_audio_thumbnail_task.py
This update closes issue #175.
> Resolve issue #175
